---
# tasks file for host_details

    - name: show fact keys
      debug:
        msg: "{{ ansible_facts.keys() }}"
      tags:
        - show_facts
    - name: Create basic information file from template
      template:
        src: basic.j2
        dest: "~/basic_info_{{ inventory_hostname }}.txt"
      tags:
        - basic_info

    - name: Create detailed information file from template
      template:
        src: detailed.j2
        dest: "~/detailed_info_{{ inventory_hostname }}.txt"
      tags:
        - detailed_info
